// DO NOT EDIT THIS FILE
// This file is generated automatically by the typed-scss-modules library
export type Styles = {
  main: string;
  sakura: string;
  sasa: string;
  tanzakuIntro: string;
  yureru: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
